### ISSUE TITLE
JobResultPathTest fails on Windows

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1032]
Tests in JobResultPathTest file fail on Windows. Problem seems to be related to paths. 

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.datacleaner.spark.JobResultPathTest.testResultPathAbolutePathSpecified(JobResultPathTest.java:62)
```

and 

```
org.junit.ComparisonFailure: 
Expected :/datacleaner/results/vanilla-job
Actual   :C:\datacleaner\results\vanilla-job
 <Click to see difference>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.datacleaner.spark.JobResultPathTest.testResultPathNameNoVariableSpecified(JobResultPathTest.java:130)
```

**Comment by LosD** [comment]
That's weird. Which branch is it?

**Comment by jhorcicka** [comment]
release 5.0

**Comment by LosD** [comment]
Even more weird. I compiled that yesterday (on Windows). Was any spark changes merged since then?
