### ISSUE TITLE
String Analyzer interprets a backslash as an escape character 

### ISSUE THREAD

**Issue by chubbard16** [datacleaner/DataCleaner#1101]
The String analyser will escapes a quote if it is immediately preceded by a backward slash. The following line

563,"87-800","WŁ","ZKI","1/74\",0,0,0,0   

will cause this exception 

org.apache.metamodel.MetaModelException: Failed to parse CSV line no. 563: 563,"87-800","WŁ","ZKI","1/74\",0,0,0,0   
	at org.apache.metamodel.csv.SingleLineCsvRow.parseLine(SingleLineCsvRow.java:99)
	at org.apache.metamodel.csv.SingleLineCsvRow.getValuesInternal(SingleLineCsvRow.java:61)
	at org.apache.metamodel.csv.SingleLineCsvRow.getValue(SingleLineCsvRow.java:111)
	at org.apache.metamodel.data.AbstractRow.getValue(AbstractRow.java:105)
	at org.datacleaner.data.MetaModelInputRow.getValueInternal(MetaModelInputRow.java:90)
	at org.datacleaner.data.AbstractInputRow.getValue(AbstractInputRow.java:48)
	at org.datacleaner.beans.StringAnalyzer.run(StringAnalyzer.java:113)
	at org.datacleaner.job.runner.AnalyzerConsumer.consumeInternal(AnalyzerConsumer.java:71)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:146)
	at org.datacleaner.job.tasks.ConsumeRowTask.execute(ConsumeRowTask.java:51)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Un-terminated quoted field at end of CSV line
	at au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:217)
	at au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:141)
	at org.apache.metamodel.csv.SingleLineCsvRow.parseLine(SingleLineCsvRow.java:96)
	... 15 more

**Comment by chubbard16** [comment]
OK found the Escape char option in the data source menu..
