### ISSUE TITLE
ClassCastException thrown when logging in to DataCloud

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1211]
This happened to me (on master branch) when logging in to DataCloud:

![image](https://cloud.githubusercontent.com/assets/291450/13599198/0483b704-e522-11e5-9f08-e025d611c3ba.png)

Before this I had deleted all `userhome/.datacleaner` folders to ensure that everything was completely clean.

Stack trace:

```
ERROR 11:34:41 DCUncaughtExceptionHandler - Thread AWT-EventQueue-0 threw uncaught exception
java.lang.ClassCastException: org.datacleaner.descriptors.ClasspathScanDescriptorProvider cannot be cast to org.datacleaner.descriptors.CompositeDescriptorProvider
	at org.datacleaner.util.RemoteServersUtils.addRemoteServer(RemoteServersUtils.java:54)
	at org.datacleaner.windows.DataCloudLogInWindow$2.run(DataCloudLogInWindow.java:292)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
```

**Comment by kaspersorensen** [comment]
Note: It does look like the conf.xml file was properly updated afterwards.
