### ISSUE TITLE
Create datastore: identical field names lead to failure despite renaming

### ISSUE THREAD

**Issue by Jan-Arie** [datacleaner/DataCleaner#1213]
If output contains identical field names (i.c. 'postal code' from both input and cleansed output)  and user  renames field(s) (on right side), then is well handled bij Write to CSV and by Write to Excel, but it leads to failure in Create Staging Table:

Column count does not match; SQL statement:
INSERT INTO adr_test VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [21002-176]

org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO adr_test VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [21002-176]

	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
        (...)

DC JOB-file:
[JOB_adr_tst_identical_field_names.analysis.txt](https://github.com/datacleaner/DataCleaner/files/163196/JOB_adr_tst_identical_field_names.analysis.txt)

INPUT file:
[nlcc-sample.txt](https://github.com/datacleaner/DataCleaner/files/163187/nlcc-sample.txt)

.

**Comment by ClaudiaPHI** [comment]
@Jan-Arie , can you give me the file "consumer-check-sample.csv" from the job ?
