### ISSUE TITLE
Export of Orders data mart example job fails

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1273]
When running the `Export of Orders data mart.analysis.xml` example job a stack-trace is logged in the execution log and the Country standardizer tab in the results windows doesn't show a valid result.

```
12:57:48ERROR: Error occurred while rendering result

found non-noded intersection between LINESTRING ( 9.971679687500028 46.32768554687496, 10.041015625000028 46.23808593750002 ) and LINESTRING ( 10.041015625 46.238085937499996, 9.971679687500023 46.32768554687497 ) [ (9.971936514839912, 46.32735366084067, NaN) ]

com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 9.971679687500028 46.32768554687496, 10.041015625000028 46.23808593750002 ) and LINESTRING ( 10.041015625 46.238085937499996, 9.971679687500023 46.32768554687497 ) [ (9.971936514839912, 46.32735366084067, NaN) ]
	at com.vividsolutions.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:130)
	at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:94)
	at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:59)
	at com.vividsolutions.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:170)
	at com.vividsolutions.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:127)
	at com.vividsolutions.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:66)
	at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:96)
	at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:58)
	at com.vividsolutions.jts.geom.Geometry.union(Geometry.java:1395)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionActual(CascadedPolygonUnion.java:384)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionUsingEnvelopeIntersection(CascadedPolygonUnion.java:343)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionOptimized(CascadedPolygonUnion.java:313)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionSafe(CascadedPolygonUnion.java:288)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:226)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:200)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:146)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:259)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:144)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:259)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:144)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:259)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:144)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.union(CascadedPolygonUnion.java:134)
	at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.union(CascadedPolygonUnion.java:80)
	at com.vividsolutions.jts.operation.union.UnaryUnionOp.union(UnaryUnionOp.java:176)
	at com.vividsolutions.jts.operation.union.UnaryUnionOp.union(UnaryUnionOp.java:95)
	at com.vividsolutions.jts.geom.Geometry.union(Geometry.java:1484)
	at com.hi.datacleaner.renderers.CountryStandardizationSwingRenderingBean.render(CountryStandardizationSwingRenderingBean.java:125)
	at com.hi.datacleaner.renderers.CountryStandardizationSwingRenderingBean.render(CountryStandardizationSwingRenderingBean.java:66)
	at org.datacleaner.panels.result.AnalyzerResultPanel$1.doInBackground(AnalyzerResultPanel.java:116)
	at org.datacleaner.panels.result.AnalyzerResultPanel$1.doInBackground(AnalyzerResultPanel.java:104)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by arjansh** [comment]
This issue only occurs in the commercial DataCleaner editions.
