### ISSUE TITLE
Error while previewing ElasticSearch data after "Insert into table"

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1312]
I was just populating an ES index with DataCleaner and wanted to preview the table (index) after doing so. The indexing seems to have gone fine, but the preview didn't work. Here's what I got in the error log:

```
ERROR 11:42:10.414 [AWT-EventQueue-0] DataSetWindow - Unexpected error occurred while building DataSetWindow contents
java.lang.NullPointerException
	at org.apache.metamodel.elasticsearch.rest.JestElasticSearchUtils.getDataFromColumnType(JestElasticSearchUtils.java:72)
	at org.apache.metamodel.elasticsearch.rest.JestElasticSearchUtils.createRow(JestElasticSearchUtils.java:50)
	at org.apache.metamodel.elasticsearch.rest.JestElasticSearchDataSet.getRow(JestElasticSearchDataSet.java:126)
	at org.apache.metamodel.data.DataSetTableModel.materialize(DataSetTableModel.java:86)
	at org.apache.metamodel.data.DataSetTableModel.getRowCount(DataSetTableModel.java:78)
	at org.datacleaner.windows.DataSetWindow.touchTableModel(DataSetWindow.java:205)
```

I can imagine this being a MetaModel issue, but I wanted to report it here first since I didn't do more investigation than this.

**Comment by kaspersorensen** [comment]
More background info.

I am using latest ElasticSearch version - 2.3.1

My datastore is using REST protocol.

I created the index manually via a HTTP poster:

```
POST http://localhost:9200/testindex1
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "person" : {
            "properties" : {
                "firstname" : { "type" : "string" },
                "lastname" : { "type" : "string" },
                "middlename" : { "type" : "string" },
                "addressline1" : { "type" : "string" },
                "addressline2" : { "type" : "string" },
                "city" : { "type" : "string" },
                "state" : { "type" : "string" },
                "zip" : { "type" : "string" }
            }
        }
    }
}
```

**Comment by kaspersorensen** [comment]
It looks like this is the same issue as reported in MetaModel:
https://issues.apache.org/jira/browse/METAMODEL-235

**Comment by ClaudiaPHI** [comment]
Issue has been fixed in metamodel
