### ISSUE TITLE
MySQL fails with referential integrity checker

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1373]
When running a referential integrity analyzer on MySQL, this exception seems to hit all rows except the first one:
```
Could not execute compiled query: Streaming result set com.mysql.jdbc.RowDataDynamic@57e1b01b is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.

org.apache.metamodel.MetaModelException: Could not execute compiled query: Streaming result set com.mysql.jdbc.RowDataDynamic@57e1b01b is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
	at org.apache.metamodel.jdbc.JdbcUtils.wrapException(JdbcUtils.java:70)
	at org.apache.metamodel.jdbc.JdbcDataContext.executeQuery(JdbcDataContext.java:331)
	at org.datacleaner.components.tablelookup.TableLookupTransformer.performQuery(TableLookupTransformer.java:419)
	at org.datacleaner.components.tablelookup.TableLookupTransformer.transform(TableLookupTransformer.java:391)
	at org.datacleaner.beans.referentialintegrity.ReferentialIntegrityAnalyzer.run(ReferentialIntegrityAnalyzer.java:126)
	at org.datacleaner.job.runner.AnalyzerConsumer.consumeInternal(AnalyzerConsumer.java:71)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:159)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:67)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:146)
	at org.datacleaner.job.tasks.ConsumeRowTask.execute(ConsumeRowTask.java:51)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@57e1b01b is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkForOutstandingStreamingData(MysqlIO.java:2747)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1911)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2618)
	at com.mysql.jdbc.StatementImpl.executeSimpleNonQuery(StatementImpl.java:1644)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2225)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.metamodel.jdbc.JdbcDataContext.execute(JdbcDataContext.java:449)
	at org.apache.metamodel.jdbc.JdbcDataContext.executeQuery(JdbcDataContext.java:326)
	... 12 more
```

This does not seem to affect other datastores. Intriguingly also doesn't seem to affect the table lookup transformer, which is a bit weird since the referential integrity analyzer more or less is using that directly.

**Comment by LosD** [comment]
Ah! The table lookup also fails if running single threaded. I guess it would have been the same if my test set was bigger than the amount of threads.

**Comment by LosD** [comment]
This change to MetaModel JdbcDataContext seems to fix it:
```java
    @Override
    public void close() {
        if (_closed) {
            return;
        }

        /* New */
        if(_resultSet != null) {
            try {
                _resultSet.close();
            } catch (SQLException e) {
                logger.warn("Closing resultset failed", e);
            }
        }

        if(_statement != null) {
            try {
                _statement.close();
            } catch (SQLException e) {
                logger.warn("Closing statement failed", e);
            }
        }
        /* End new */
        
        if (_jdbcDataContext != null) {
            _jdbcDataContext.close(_connection, _resultSet, _statement);
        }
        if (_compiledQuery != null) {
            _compiledQuery.returnLease(_lease);
        }
        _closed = true;
    }
```

It breaks some tests though, so not creating a MM PR just yet... Also still trying to find out why no _jdbcDataContext is null in the first place.

**Comment by kaspersorensen** [comment]
I know it isn't quite a "solution" (but a workaround), but I just wanted to quickly also mention #1376 as a potentially related issue/suggestion. Not that it would ever replace the bugfix that is needed here.

**Comment by LosD** [comment]
Fixed in [METAMODEL-1093](https://issues.apache.org/jira/browse/METAMODEL-1093)
