### ISSUE TITLE
Synonym and Referencedata datastore fail at Preview

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1511]
Synonym and Reference data datastore fail at Preview 

The datastores belongs to a SQL database. I have used the sample database from Microsoft "AdventureWorks2012"

![image](https://cloud.githubusercontent.com/assets/6339923/18471635/24033aca-79b3-11e6-9253-d7e16a0d5d32.png)

```
PreviewTransformedDataActionListener - Preview data error
java.lang.IllegalArgumentException: No such table: Department
	at org.apache.metamodel.query.builder.InitFromBuilderImpl.from(InitFromBuilderImpl.java:80)
	at org.datacleaner.reference.DatastoreSynonymCatalog.loadIntoMemory(DatastoreSynonymCatalog.java:136)
	at org.datacleaner.reference.DatastoreSynonymCatalog.openConnection(DatastoreSynonymCatalog.java:97)
	at org.datacleaner.beans.transform.SynonymLookupTransformer.init(SynonymLookupTransformer.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.datacleaner.descriptors.AbstractMethodDescriptor.invoke(AbstractMethodDescriptor.java:79)
	at org.datacleaner.descriptors.InitializeMethodDescriptorImpl.initialize(InitializeMethodDescriptorImpl.java:44)
	at org.datacleaner.lifecycle.LifeCycleHelper.initialize(LifeCycleHelper.java:180)
	at org.datacleaner.job.tasks.InitializeTask.executeInternal(InitializeTask.java:83)
	at org.datacleaner.job.tasks.InitializeTask.execute(InitializeTask.java:55)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by ClaudiaPHI** [comment]
![image](https://cloud.githubusercontent.com/assets/6339923/18471880/2fa2d344-79b4-11e6-8bb1-a8a1f529428a.png)
