### ISSUE TITLE
Sample Pentaho job in monitor fails

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1512]
DataCleaner Monitor contains a number of default jobs, one of them being the Sample Pentaho job.

When I run this job, it fails with this stacktrace:

```
 - Job execution failed: ExecutionLog[job=JobIdentifier[name=Sample Pentaho job],
 - Failure stack trace:
org.datacleaner.monitor.pentaho.PentahoJobException: Failed to invoke HTTP request: Connect to localhost:8081 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
        at org.datacleaner.monitor.pentaho.PentahoCarteClient.execute(PentahoCarteClient.java:119) ~[DataCleaner-monitor-pentaho-job-engine-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.pentaho.PentahoCarteClient.getAvailableTransformations(PentahoCarteClient.java:90) ~[DataCleaner-monitor-pentaho-job-engine-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.pentaho.PentahoJobEngine.fillMissingDetails(PentahoJobEngine.java:158) ~[DataCleaner-monitor-pentaho-job-engine-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.pentaho.PentahoJobEngine.executeJob(PentahoJobEngine.java:107) ~[DataCleaner-monitor-pentaho-job-engine-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.scheduling.quartz.ExecuteJob.executeJob(ExecuteJob.java:169) [DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.scheduling.quartz.ExecuteJob.executeInternal(ExecuteJob.java:114) [DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75) [spring-context-support-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.1.7.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-2.1.7.jar:na]
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8081 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.4.1.jar:4.4.1]
        at org.datacleaner.monitor.pentaho.PentahoCarteClient.execute(PentahoCarteClient.java:117) ~[DataCleaner-monitor-pentaho-job-engine-5.1.3-SNAPSHOT.jar:na]
        ... 8 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_92]
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[na:1.8.0_92]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_92]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_92]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_92]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_92]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_92]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_92]
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74) ~[httpclient-4.4.1.jar:4.4.1]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.4.1.jar:4.4.1]
        ... 17 common frames omitted
```

This is probably caused by the fact that something else needs to be in place to make this job run successfully, but that is not indicated in DataCleaner Monitor.

**Comment by LosD** [comment]
Let's add a way to describe jobs, both for preset jobs and user-made

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
