### ISSUE TITLE
Contributor name cleansing job in monitor fails

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1514]
DataCleaner Monitor contains a number of default jobs, one of them being the Contributor name cleansing job.

When I run this job, it fails with these stacktraces:

```
16:05:02.417 [scheduler_Worker-3] WARN  o.d.m.s.l.JobFailedEventLoggerListener - Job execution failed: ExecutionLog[job=JobIdentifier[name=Contributor name cleansing], ExecutionIdentifier[begin=Wed Sep 14 16:05:02 CEST 2016, status=FAILURE]]
16:05:02.422 [scheduler_Worker-3] INFO  o.d.m.s.l.JobFailedEventLoggerListener - Failure stack trace:
org.datacleaner.job.NoSuchComponentException: No such TransformerType descriptor: EasyDQ Name cleansing
        at org.datacleaner.job.JaxbJobReader.createComponentBuilder(JaxbJobReader.java:595) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.configureComponents(JaxbJobReader.java:487) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:467) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:409) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:344) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader$2.eval(MonitorJobReader.java:93) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader$2.eval(MonitorJobReader.java:73) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.repository.file.FileRepositoryFile.readFile(FileRepositoryFile.java:149) ~[DataCleaner-engine-core-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader.readJob(MonitorJobReader.java:98) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader.readJob(MonitorJobReader.java:55) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.job.DataCleanerJobContextImpl.getAnalysisJob(DataCleanerJobContextImpl.java:107) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.job.DataCleanerJobEngine.executeJob(DataCleanerJobEngine.java:169) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.scheduling.quartz.ExecuteJob.executeJob(ExecuteJob.java:169) [DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.scheduling.quartz.ExecuteJob.executeInternal(ExecuteJob.java:114) [DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75) [spring-context-support-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.1.7.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-2.1.7.jar:na]
16:05:02.472 [scheduler_Worker-3] INFO  o.d.m.scheduling.quartz.ExecuteJob - Finished quartz job with key: demo.Contributor name cleansing - org.datacleaner.monitor.scheduling.quartz.ExecuteJob@2814f581
16:05:02.477 [scheduler_Worker-4] INFO  o.d.m.scheduling.quartz.ExecuteJob - Executing quartz job with key: demo.Customer duplicates - org.datacleaner.monitor.scheduling.quartz.ExecuteJob@715d4e46
16:05:02.482 [scheduler_Worker-4] INFO  o.d.m.scheduling.quartz.ExecuteJob - Tenant demo executing job JobIdentifier[name=Customer duplicates]
16:05:03.136 [scheduler_Worker-4] WARN  o.d.m.s.l.JobFailedEventLoggerListener - Job execution failed: ExecutionLog[job=JobIdentifier[name=Customer duplicates], ExecutionIdentifier[begin=Wed Sep 14 16:05:02 CEST 2016, status=FAILURE]]
16:05:03.139 [scheduler_Worker-4] INFO  o.d.m.s.l.JobFailedEventLoggerListener - Failure stack trace:
org.datacleaner.job.NoSuchComponentException: No such AnalyzerType descriptor: Duplicate Detection
        at org.datacleaner.job.JaxbJobReader.createComponentBuilder(JaxbJobReader.java:595) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.configureComponents(JaxbJobReader.java:487) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:467) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:409) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:344) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader$2.eval(MonitorJobReader.java:93) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader$2.eval(MonitorJobReader.java:73) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.repository.file.FileRepositoryFile.readFile(FileRepositoryFile.java:149) ~[DataCleaner-engine-core-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader.readJob(MonitorJobReader.java:98) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.MonitorJobReader.readJob(MonitorJobReader.java:55) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.job.DataCleanerJobContextImpl.getAnalysisJob(DataCleanerJobContextImpl.java:107) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.job.DataCleanerJobEngine.executeJob(DataCleanerJobEngine.java:169) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.scheduling.quartz.ExecuteJob.executeJob(ExecuteJob.java:169) [DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.scheduling.quartz.ExecuteJob.executeInternal(ExecuteJob.java:114) [DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75) [spring-context-support-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.1.7.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-2.1.7.jar:na]
```

It seems like some types of transformers are missing.

**Comment by ClaudiaPHI** [comment]
The sample job for commercial edition fails for this job because of invalid of credentials.

**Comment by ClaudiaPHI** [comment]
This exception occurs for community edition.
