### ISSUE TITLE
Job with concatenator fails using run first N records

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1531]
I have a job which contains a Plain search/replace, a Concatenator and an output write, which runs successfully when executed normally, but fails when run using the run first N records option. It results in a stacktrace which in itself doesn't explain very much:

```
13:48:16ERROR: An error occurred in the analysis job!

org.datacleaner.job.ComponentValidationException
	at org.datacleaner.descriptors.ValidateMethodDescriptorImpl.convertThrownException(ValidateMethodDescriptorImpl.java:42)
	at org.datacleaner.descriptors.AbstractMethodDescriptor.invoke(AbstractMethodDescriptor.java:83)
	at org.datacleaner.descriptors.ValidateMethodDescriptorImpl.validate(ValidateMethodDescriptorImpl.java:37)
	at org.datacleaner.lifecycle.LifeCycleHelper.validate(LifeCycleHelper.java:160)
	at org.datacleaner.job.tasks.InitializeTask.executeInternal(InitializeTask.java:71)
	at org.datacleaner.job.tasks.InitializeTask.execute(InitializeTask.java:55)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```

**Comment by arjansh** [comment]
![2016-09-27 13_44_35-test analysis xml _ customers _ analysis job _ datacleaner](https://cloud.githubusercontent.com/assets/16542747/18872143/31ddad86-84b9-11e6-8211-2e4d3e1ed5f6.png)
![2016-09-27 13_45_04-test analysis xml _ customers _ analysis results _ datacleaner](https://cloud.githubusercontent.com/assets/16542747/18872144/3592b5f2-84b9-11e6-8824-f34484811835.png)

**Comment by arjansh** [comment]
![2016-09-27 13_45_04-test analysis xml _ customers _ analysis results _ datacleaner](https://cloud.githubusercontent.com/assets/16542747/18872148/3fc3a8e2-84b9-11e6-8630-0512b0a065f6.png)

**Comment by arjansh** [comment]
[test.analysis.xml.zip](https://github.com/datacleaner/DataCleaner/files/495395/test.analysis.xml.zip)

**Comment by arjansh** [comment]
This seems to be a new issue in 5.1.3, because I can't reproduce it in 5.1.2.

**Comment by arjansh** [comment]
I think that outside the problem itself also the logged message should be addressed so it provides more information regarding to what goes wrong.

**Comment by arjansh** [comment]
This seems to be a regression introduced by https://github.com/datacleaner/DataCleaner/pull/1482.
