### ISSUE TITLE
Sporading StackOverflowError / ImageWatched error blocks application usage

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#163]
Seems to happen sometimes on particular machines, no particular reason or common environment variables identified. Seems to only happen after the job graph UI was introduced.

```
java.lang.StackOverflowError
                at sun.awt.image.ImageWatched$WeakLink.removeWatcher(Unknown Source)
                at sun.awt.image.ImageWatched$WeakLink.removeWatcher(Unknown Source)
                at sun.awt.image.ImageWatched$WeakLink.removeWatcher(Unknown Source)
```

**Comment by kaspersorensen** [comment]
Closing this. Seems to be very JRE specific and all references to the issue I found did not present a solution.
