### ISSUE TITLE
DC 5.8.0: Guice injection null error

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1913]
Upon testing the release 5.8.0 packaged binary, I get this error:

```
Using DATACLEANER_HOME: C:\Users\kasper\git\DataCleaner\target\checkout\desktop\ui\target\DataCleaner-5.8.0\DataCleaner\
Using DATACLEANER_LIB_HOME: C:\Users\kasper\git\DataCleaner\target\checkout\desktop\ui\target\DataCleaner-5.8.0\DataCleaner\
Using DATACLEANER_JAVA_OPTS= -Xmx1024m
Using default log configuration: jar:file:/C:/Users/kasper/git/DataCleaner/target/checkout/desktop/ui/target/DataCleaner-5.8.0/DataCleaner/DataCleaner.jar!/org/datacleaner/log4j-default.xml
Failed to load DataCleaner version from manifest: inStream parameter is null
Failed to load DataCleaner version from manifest: inStream parameter is null
22:48:38.090 [main] ERROR org.datacleaner.bootstrap.Bootstrap - An unexpected error has occurred during bootstrap. Exiting with status code -2.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/NullInjectedIntoNonNullable]: null returned by binding at DCModuleImpl.getUndecoratedAnalyzerBeansConfiguration()
 but the 1st parameter of DCModuleImpl.getDataCleanerConfiguration(DCModuleImpl.java:256) is not @Nullable
  at DCModuleImpl.getUndecoratedAnalyzerBeansConfiguration(DCModuleImpl.java:250)
  at DCModuleImpl.getUndecoratedAnalyzerBeansConfiguration(DCModuleImpl.java:250)
  at DCModuleImpl.getDataCleanerConfiguration(DCModuleImpl.java:256)
      \_ for 1st parameter
  at DCModuleImpl.getDataCleanerConfiguration(DCModuleImpl.java:256)
  while locating DataCleanerConfiguration

Learn more:
  https://github.com/google/guice/wiki/NULL_INJECTED_INTO_NON_NULLABLE

1 error

======================
Full classname legend:
======================
DCModuleImpl:             "org.datacleaner.guice.DCModuleImpl"
DataCleanerConfiguration: "org.datacleaner.configuration.DataCleanerConfiguration"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[guice-5.1.0.jar:?]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1104) ~[guice-5.1.0.jar:?]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139) ~[guice-5.1.0.jar:?]
        at org.datacleaner.bootstrap.Bootstrap.runInternal(Bootstrap.java:177) ~[DataCleaner.jar:5.8.0]
        at org.datacleaner.bootstrap.Bootstrap.run(Bootstrap.java:92) [DataCleaner.jar:5.8.0]
        at org.datacleaner.Main.main(Main.java:165) [DataCleaner.jar:5.8.0]
        at org.datacleaner.Main.main(Main.java:150) [DataCleaner.jar:5.8.0]
```

**Comment by kaspersorensen** [comment]
Two observations before I give up for tonight:

- It does work fine with Java 8. So my guess is that we didn't fix Java 9+ support fully.
- I am having trouble getting anything useful out of logging. I have a feeling that the log4j config is not being loaded properly because no matter how I change it, I only seem to be getting ERROR level logs.
