### ISSUE TITLE
ConvertToDateTransformerTest Fails in CDT and EST 

### ISSUE THREAD

**Issue by maphysics** [datacleaner/DataCleaner#283]
ConvertToDateTransformerTest is time zone dependent and causes datacleaner-core to fail to compile

ERROR:
junit.framework.ComparisonFailure: 
Expected :1997-05-19
Actual   :1997-05-18
 <Click to see difference>
	at org.datacleaner.components.convert.ConvertToDateTransformerTest.testConvertFromNumber(ConvertToDateTransformerTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

INVESTOGATION:
ConvertToDateTransformerTest.java:68:
      assertEquals("1997-05-19", format(transformer.convertFromNumber(10000)));

calls into org/datacleaner/components/convert/ConvertToDateTransformer.java:230: 
      return new Date(longValue * 1000 * 60 * 60 * 24);

accoriding to http://www.epochconverter.com/

864000000000 =>

GMT: Mon, 19 May 1997 00:00:00 GMT
Your time zone: 5/18/1997, 7:00:00 PM GMT-5:00 DST

CONCLUSION:
Commenting out that assert allows the test to finish.  However, it's likely the other asserts will have issues in other time zones.  The test is time zone dependent as it isn't running in UTC time.  Should the test be set to UTC time or should the transform be made time zone aware? Please advice as to the preferred fix.

**Comment by kaspersorensen** [comment]
For now I made the unittest fixed to CET time. I think it's very valid to add to the transformer an option to specify a timezone. As long as the defualt behaviour stays the same (which is to keep the machines' current timezone).

**Comment by kaspersorensen** [comment]
Thank you for the bug report by the way! :)

**Comment by maphysics** [comment]
Awesome!  Thanks for fixing that so quickly!  Perhaps we can make the transform option an enhancement request.

**Comment by kaspersorensen** [comment]
Please raise it as a new issue.
