### ISSUE TITLE
ConvertToDateTransformerTest Fails in CDT testConvertFromString Fails

### ISSUE THREAD

**Issue by maphysics** [datacleaner/DataCleaner#293]
Test fails as ConvertToDateTransformer.convertFromString converts to date in local time, CDT, then the test is in CET.  Therefore moving the result ahead one day.

junit.framework.ComparisonFailure: 
Expected :2012-04-26
Actual   :2012-04-27
  <Click to see difference>

	at org.datacleaner.components.convert.ConvertToDateTransformerTest.testConvertFromString(ConvertToDateTransformerTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by kaspersorensen** [comment]
Can you try again? I believe it is fixed now.

**Comment by maphysics** [comment]
Just saw your comment, trying now

**Comment by maphysics** [comment]
builds now :) thanks

**Comment by maphysics** [comment]
wrong button

**Comment by kaspersorensen** [comment]
It still didn't build, or?

**Comment by maphysics** [comment]
It still builds fine.  I reopened it because I figured that the process wasn't for me to close it.

**Comment by kaspersorensen** [comment]
Ah cool, then I'll close it :-)
