### ISSUE TITLE
Weird stacktrace writing to CSV file

### ISSUE THREAD

**Issue by manuelvandenberg** [datacleaner/DataCleaner#463]
With DC4.0.4, observed the following stacktrace when writing a part of a file (using a filter) to a CSV file. The CSV file is fully written, all records are present, but just before completing the job, the following stack trace appears in the progress window:
```
java.lang.NullPointerException
 at org.datacleaner.extension.output.CreateCsvFileAnalyzer.getResultInternal(CreateCsvFileAnalyzer.java:197)
 at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.getResult(AbstractOutputWriterAnalyzer.java:53)
 at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.getResult(AbstractOutputWriterAnalyzer.java:34)
 at org.datacleaner.job.tasks.CollectResultsTask.execute(CollectResultsTask.java:60)
 at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
```

Worth a look, especially since the trace doesn't contain a lot of information as to what is wrong.

**Comment by kaspersorensen** [comment]
Confirmed what the cause is of this: If separator, quote or escape character is not defined (null) then an autoboxing operation will go wrong and throw the NPE.

**Comment by manuelvandenberg** [comment]
In this case, separator was filled, but escape and quote char were (intentionally) empty.
Oddly enough, all data is written and the npe happens only when the job is almost complete.

**Comment by kaspersorensen** [comment]
Yeah I think that happened at the time when it tried to sort the final file. Anyways - there's a pull request to avoid the unboxing issue now: #466
