### ISSUE TITLE
Strange exceptions in create CSV writer

### ISSUE THREAD

**Issue by drexler42** [datacleaner/DataCleaner#485]
A sample job reads some values from a CSV file, performs a name validation on the records, and then writes a new CSV file with the results. 

![2015-06-18 16_15_17-auto csv _ analysis job _ datacleaner](https://cloud.githubusercontent.com/assets/5919509/8233241/73a70f5e-15d5-11e5-9826-ffe4db16aca1.png)

This job throws an exception when it runs.

```
ava.lang.ArrayIndexOutOfBoundsException


16:17:22ERROR: An error occurred in the analyzer: Create CSV file (25 columns)

java.lang.ArrayIndexOutOfBoundsException


16:17:22ERROR: An error occurred in the analyzer: Create CSV file (25 columns)

java.lang.ArrayIndexOutOfBoundsException


16:17:22ERROR: An error occurred in the analyzer: Create CSV file (25 columns)

java.lang.ArrayIndexOutOfBoundsException
```

The problem is in the mapping of the output fields. When configured like this, the problem does not appear:

![2015-06-18 16_20_17-auto txt _ datacleaner](https://cloud.githubusercontent.com/assets/5919509/8233322/f5ba5cd0-15d5-11e5-8f19-8496ec47dd8e.png)

But when configured like this, the exception happens:

![2015-06-18 16_18_47-auto txt _ datacleaner](https://cloud.githubusercontent.com/assets/5919509/8233295/c9cefda6-15d5-11e5-9c14-c4456fc32d03.png)

In this case the problem is caused by the (commercial) Name transformer, but I suspect the underlying problem is a general problem in the name mapping of the create CSV writer.

**Comment by kaspersorensen** [comment]
I tried to reproduce with a simple concatenation transformer:

![image](https://cloud.githubusercontent.com/assets/291450/8254561/d39a06ae-1699-11e5-8045-f44572d248e2.png)

But I couldn't ... that all worked fine. Can you share anything else about the error - maybe a stack trace?

**Comment by drexler42** [comment]
There is no more in terms of stack trace. Both the console as the job window repeat the error lines as shown above, but not a complete stack trace. I will try to reproduce with other components...

**Comment by kaspersorensen** [comment]
Weird. Normally an error would always be reported there with a full stack I think...

If you reproduce (either with other or the same Name component) feel free to email me the analysis.xml file for inspection/reproduction.

**Comment by LosD** [comment]
We've seen something similar in DataImprover. Does the input or output have two columns with the same name, but different capitalization? My guess would be that DataCleaner considers them as two different names, but MetaModel does not, creating all kinds of trouble.

**Comment by drexler42** [comment]
I managed to get a stack trace

```
15:12:47ERROR: An error occurred in the analyzer: Create CSV file (25 columns)

24

java.lang.ArrayIndexOutOfBoundsException: 24
	at org.apache.metamodel.data.AbstractRowBuilder.value(AbstractRowBuilder.java:108)
	at org.apache.metamodel.data.AbstractRowBuilder.value(AbstractRowBuilder.java:103)
	at org.datacleaner.output.AbstractMetaModelOutputWriter$1.run(AbstractMetaModelOutputWriter.java:92)
	at org.apache.metamodel.csv.CsvDataContext.executeUpdate(CsvDataContext.java:429)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.flushBuffer(AbstractMetaModelOutputWriter.java:85)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.addToBuffer(AbstractMetaModelOutputWriter.java:78)
	at org.datacleaner.output.MetaModelOutputRow.write(MetaModelOutputRow.java:62)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.writeRow(AbstractOutputWriterAnalyzer.java:79)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.run(AbstractOutputWriterAnalyzer.java:68)
	at org.datacleaner.job.runner.AnalyzerConsumer.consumeInternal(AnalyzerConsumer.java:81)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:147)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:67)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.processNext(ConsumeRowHandlerDelegate.java:90)
	at org.datacleaner.job.runner.TransformerConsumer.consumeInternal(TransformerConsumer.java:125)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:147)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:147)
	at org.datacleaner.job.tasks.ConsumeRowTask.execute(ConsumeRowTask.java:51)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by drexler42** [comment]
Yes, it seems to be something like that. I put a break point at AbstractRowBuilder line 108. What I get is that the `values` array has one entry less than expected. Dennis is right. The job has 2 columns, "Gender" and "GENDER". The problem is caused by that.

I am not sure on how to proceed. Please advise.

**Comment by kaspersorensen** [comment]
My advice to proceed: Check how the table/header is getting created. I think this happens in AbstractOutputWriterAnalyzer or it's CSV-specific subclass.

**Comment by drexler42** [comment]
I observe the following:

CsvOutputWriterFactory.getWriter() iterates over the headers, invoking the table builder on each. The tableBuilder object is of type CsvCreateTableBuilder.
```
                dataContext.executeUpdate(new UpdateScript() {
                    @Override
                    public void run(UpdateCallback callback) {
                        TableCreationBuilder tableBuilder = callback.createTable(schema, "table");
                        for (String header : headers) {
                            tableBuilder.withColumn(header);
                        }
                        tableBuilder.execute();
                    }
                });
```
The csvCreateTableBuilder extends AbstractTableCreationBuilder.
AbstractTableCreationBuilder only adds a column if getColumnByName does not return a column by the same name. This causes only 1 column to be created when columns have the same name.
```
    @Override
    public ColumnCreationBuilder withColumn(String name) {
        logger.debug("withColumn({})", name);
        MutableColumn col = (MutableColumn) _table.getColumnByName(name);
        if (col == null) {
            col = new MutableColumn(name).setTable(_table).setColumnNumber(_table.getColumnCount());
            _table.addColumn(col);
        }
        return new ColumnCreationBuilderImpl(this, col);
    }
```
The end result is a data context with less fields then there are headers. This seems wrong to me. The CsvCreateTableBuilder should always create columns for all headers, even if the names are duplicate...
I will override the withColumn() method in CsvCreateTableBuilder, and see if that helps fixing this problem.

**Comment by drexler42** [comment]
Hmm. Problem would of course be how to identify the columns. getColumnByName() certainly would fail. Should DC complain about Csv files with duplicate column names? Or can MetaModel setup aliases like "column1", "column2", ...

**Comment by drexler42** [comment]
BTW, this problem can be easily reproduced by creating a CSV datastore for a file like this:
```
Gender|Gender
"M"|"M"
"M"|"F"
"F"|"M"
"F"|"F"
```
And then using a Create CSV writer to attempt to write the file unmodified.

**Comment by arjansh** [comment]
I'm unable to reproduce this issue on DataCleaner 5.1.2.

With MetaModel 4.5.3 duplicate column names are automatically made unique (by default by adding a number to the duplicate occurrences of a column name). DataCleaner 5.1 and higher use MetaModel 4.5.3 or higher.
