### ISSUE TITLE
build DataCleaner-4.0.8  with maven failed.

### ISSUE THREAD

**Issue by GideonYi** [datacleaner/DataCleaner#498]
I am trying to build datecleaner with maven,but get the following error:

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project DataCleaner-basic-transformers: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project DataCleaner-basic-transformers: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:490)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at scala_maven_executions.JavaMainCallerByFork.run(JavaMainCallerByFork.java:100)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:161)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	... 21 more

tihs is my environment:
Maven home: E:\LocalServer\apache-maven-3.0.5
Java version: 1.7.0_67, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_67\jre
Default locale: en_US, platform encoding: GBK
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

Is any one meet the same issue with me?  or provider your successful environment, so I can have a try. thanks a lot.

**Comment by kaspersorensen** [comment]
Looks like it is one of the maven plugins that is failing. Could you try with a newer Maven version? Maybe it requires 3.1, 3.2 or so.

**Comment by GideonYi** [comment]
Thans for the reply, but I still got the error after changed the maven to version 3.2.5.
Here is the related error message with the -X arguements from maven:

[DEBUG] plugin jar to add :E:\LocalServer\repository-maven\repository\net\alchim31\maven\scala-maven-plugin\3.2.0\scala-maven-plugin-3.2.0.jar
[DEBUG] cmd:  C:\Program Files\Java\jdk1.7.0_67\jre\bin\java -Xbootclasspath/a:E:\LocalServer\repository-maven\repository\org\scala-lang\scala-library\2.11.4\scala-library-2.11.4.jar;E:\LocalServer\repository-maven\repository\org\scala-lang\scala-compiler\2.11.4\scala-compiler-2.11.4.jar -classpath E:\LocalServer\repository-maven\repository\net\alchim31\maven\scala-maven-plugin\3.2.0\scala-maven-plugin-3.2.0.jar scala_maven_executions.MainWithArgsInFile scala.tools.nsc.Main C:\Users\Gideon\AppData\Local\Temp\scala-maven-5974482103161362679.args
[ERROR] java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
[INFO] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[INFO] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
[INFO] 	at java.lang.Class.getMethod0(Class.java:2813)
[INFO] 	at java.lang.Class.getMethod(Class.java:1663)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:155)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DataCleaner parent ................................. SUCCESS [ 10.823 s]
[INFO] DataCleaner-api .................................... SUCCESS [  7.107 s]
[INFO] DataCleaner-testware ............................... SUCCESS [  1.991 s]
[INFO] DataCleaner engine ................................. SUCCESS [  0.013 s]
[INFO] DataCleaner-engine-core ............................ SUCCESS [  8.511 s]
[INFO] DataCleaner-engine-utils ........................... SUCCESS [  0.251 s]
[INFO] DataCleaner-env .................................... SUCCESS [  0.100 s]
[INFO] DataCleaner-env-berkeleydb ......................... SUCCESS [  0.547 s]
[INFO] DataCleaner-env-h2 ................................. SUCCESS [  0.486 s]
[INFO] DataCleaner-components ............................. SUCCESS [  0.116 s]
[INFO] DataCleaner-basic-transformers ..................... FAILURE [  7.824 s]
[INFO] DataCleaner-basic-filters .......................... SKIPPED
[INFO] DataCleaner-html-rendering ......................... SKIPPED
[INFO] DataCleaner-basic-analyzers ........................ SKIPPED
[INFO] DataCleaner-pattern-finder ......................... SKIPPED
[INFO] DataCleaner-value-distribution ..................... SKIPPED
[INFO] DataCleaner-reference-data ......................... SKIPPED
[INFO] DataCleaner-date-gap ............................... SKIPPED
[INFO] DataCleaner-standardizers .......................... SKIPPED
[INFO] DataCleaner-i18n ................................... SKIPPED
[INFO] DataCleaner-el ..................................... SKIPPED
[INFO] DataCleaner-xml-config ............................. SKIPPED
[INFO] DataCleaner-desktop ................................ SKIPPED
[INFO] DataCleaner-desktop-api ............................ SKIPPED
[INFO] DataCleaner-writers ................................ SKIPPED
[INFO] DataCleaner-env-cluster ............................ SKIPPED
[INFO] DataCleaner-data-structures ........................ SKIPPED
[INFO] DataCleaner-uniqueness ............................. SKIPPED
[INFO] DataCleaner-referential-integrity .................. SKIPPED
[INFO] DataCleaner-json ................................... SKIPPED
[INFO] DataCleaner-sample-extension ....................... SKIPPED
[INFO] DataCleaner-visualization .......................... SKIPPED
[INFO] DataCleaner-network-tools .......................... SKIPPED
[INFO] DataCleaner-javascript ............................. SKIPPED
[INFO] DataCleaner-desktop-ui ............................. SKIPPED
[INFO] DataCleaner monitor modules ........................ SKIPPED
[INFO] DataCleaner-monitor-api ............................ SKIPPED
[INFO] DataCleaner-monitor-services ....................... SKIPPED
[INFO] DataCleaner-monitor-widgets ........................ SKIPPED
[INFO] DataCleaner-monitor-extensions ..................... SKIPPED
[INFO] DataCleaner-monitor-pentaho-job-engine ............. SKIPPED
[INFO] DataCleaner-monitor-jdbc-datastore-wizards ......... SKIPPED
[INFO] DataCleaner-monitor-csv-datastore-wizard ........... SKIPPED
[INFO] DataCleaner-monitor-excel-datastore-wizard ......... SKIPPED
[INFO] DataCleaner-monitor-salesforce-datastore-wizard .... SKIPPED
[INFO] DataCleaner-monitor-sugarcrm-datastore-wizard ...... SKIPPED
[INFO] DataCleaner-monitor-quick-analysis-wizard .......... SKIPPED
[INFO] DataCleaner-monitor-copy-data-wizard ............... SKIPPED
[INFO] DataCleaner-monitor-completeness-analysis-wizard ... SKIPPED
[INFO] DataCleaner-monitor-ui ............................. SKIPPED
[INFO] DataCleaner documentation .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.977 s
[INFO] Finished at: 2015-07-10T21:07:33+08:00
[INFO] Final Memory: 71M/1173M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project DataCleaner-basic-transformers: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project DataCleaner-basic-transformers: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:490)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at scala_maven_executions.JavaMainCallerByFork.run(JavaMainCallerByFork.java:100)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:161)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	... 21 more
[ERROR]
