### ISSUE TITLE
Error while saving a job that uses the class HDFS Resource

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#525]
I am working on making it possible to write a CSV file to a Resource instead of a File, but I face this problem when trying to save my jobs. 
Original Issue: #494 
![screen shot 2015-07-23 at 12 06 16 pm](https://cloud.githubusercontent.com/assets/6339923/8849298/e98c79aa-313e-11e5-9015-ef870b516eba.png)

**Comment by kaspersorensen** [comment]
Please also include a stack trace or else we'll be searching in the dark.

**Comment by ClaudiaPHI** [comment]
StackTrace: 
'''
ERROR 15:55:59 DCUncaughtExceptionHandler - Thread AWT-EventQueue-0 threw uncaught exception
java.lang.IllegalStateException: Could not find a resource handler for resource: org.apache.metamodel.util.HdfsResource@c0e0e3f9
	at org.datacleaner.util.convert.ResourceConverter.toString(ResourceConverter.java:176)
	at org.datacleaner.util.convert.ResourceConverter.toString(ResourceConverter.java:45)
	at org.datacleaner.util.convert.DelegatingConverter.toString(DelegatingConverter.java:129)
	at org.datacleaner.util.convert.StringConverter.serialize(StringConverter.java:165)
	at org.datacleaner.util.convert.StringConverter.serialize(StringConverter.java:138)
	at org.datacleaner.job.JaxbJobWriter.createPropertyConfiguration(JaxbJobWriter.java:350)
	at org.datacleaner.job.JaxbJobWriter.addConfiguration(JaxbJobWriter.java:276)
	at org.datacleaner.job.JaxbJobWriter.write(JaxbJobWriter.java:166)
	at org.datacleaner.actions.SaveAnalysisJobActionListener.actionPerformed(SaveAnalysisJobActionListener.java:192)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
'''
