### ISSUE TITLE
Null Filter on Elasticsearch Uses Wrong Type of Query

### ISSUE THREAD

**Issue by maphysics** [datacleaner/DataCleaner#610]
A null filter used to select data from an Elasticsearch datastore will use a term filter with a null value instead of an not with an exists filter to check for the presence of the field.  The term filter produces an error from Elasticsearch when filtering on a date field.  

```
Failed to execute phase [query], all shards failed; shardFailures {[lckVlrIBRfCZt7iRZJIRmw][index][0]: RemoteTransportException[[iad1esdn5vz39][inet[ip-address]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[index][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":{"term":{"data.date":null}}}}}]]]; nested: IllegalArgumentException[Invalid format: "null"]; }{[lckVlrIBRfCZt7iRZJIRmw][index][1]: RemoteTransportException[[iad1esdn5vz39][inet[ip address]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[index][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":{"term":{"data.date":null}}}}}]]]; nested: IllegalArgumentException[Invalid format: "null"]; }{[wBZD9eocS5SDbjKw4VExQg][index][2]: RemoteTransportException[[iad1esdn2vz22][inet[ip address]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[index][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":{"term":{"data.date":null}}}}}]]]; nested: IllegalArgumentException[Invalid format: "null"]; }{[wBZD9eocS5SDbjKw4VExQg]index[3]: RemoteTransportException[[iad1esdn2vz22][inet[ip address][indices:data/read/search[phase/query]]]; nested: SearchParseException[[index][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":{"term":{"data.date":null}}}}}]]]; nested: IllegalArgumentException[Invalid format: "null"]; }{[wBZD9eocS5SDbjKw4VExQg][index][4]: RemoteTransportException[[iad1esdn2vz22][inet[ip address]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[index][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":{"term":{"data.date":null}}}}}]]]; nested: IllegalArgumentException[Invalid format: "null"]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:237)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:183)
	at org.elasticsearch.search.action.SearchServiceTransportAction$6.handleException(SearchServiceTransportAction.java:249)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleException(MessageChannelHandler.java:190)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:180)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:130)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:
```

**Comment by kaspersorensen** [comment]
Thanks for reporting this. I actually think this is an Apache MetaModel issue then. Our null check filter "just" creates a MetaModel query with a logical "WHERE x IS NULL" or "WHERE x IS NOT NULL" clause. It seems this is not properly translated into the physical ElasticSearch query. I will report the issue on the MM bugtracker and post the issue reference here.

**Comment by kaspersorensen** [comment]
MetaModel bug reported: https://issues.apache.org/jira/browse/METAMODEL-184

**Comment by maphysics** [comment]
+1

**Comment by LosD** [comment]
Pull request here: https://github.com/apache/metamodel/pull/48

**Comment by kaspersorensen** [comment]
I believe this should be fixed.

Maybe you would like to verify this for us @maphysics - if so please send me a mail and I will give you a download link.

**Comment by maphysics** [comment]
Hi Kasper,

I just saw this email.  I should be able to verify it on Monday.  Shoot me
the link.

Missy
