### ISSUE TITLE
A component is sometimes wiped out when linking it to an output data stream

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#622]
Sometimes (not sure why it works in many situations, but fails in the other) when trying to link component to an output data stream (e.g. link a component to "Complete rows" of a Completeness Analyzer), the component disappears from the canvas.

An exception appeared in the log:
```
ERROR 09:31:36 AbstractPropertyWidget - Exception occurred in widget batch update, fireValueChanged() will not be invoked
java.lang.NullPointerException
	at org.datacleaner.widgets.properties.MultipleInputColumnsPropertyWidget.getOrCreateCheckBoxDecoration(MultipleInputColumnsPropertyWidget.java:555)
	at org.datacleaner.widgets.properties.MultipleInputColumnsPropertyWidget.reorderValue(MultipleInputColumnsPropertyWidget.java:535)
	at org.datacleaner.widgets.properties.MultipleInputColumnsPropertyWidget$5.run(MultipleInputColumnsPropertyWidget.java:208)
	at org.datacleaner.widgets.properties.AbstractPropertyWidget.batchUpdateWidget(AbstractPropertyWidget.java:87)
	at org.datacleaner.widgets.properties.MultipleInputColumnsPropertyWidget.initialize(MultipleInputColumnsPropertyWidget.java:205)
	at org.datacleaner.widgets.properties.MultipleInputColumnsPropertyWidget.initialize(MultipleInputColumnsPropertyWidget.java:1)
	at org.datacleaner.widgets.properties.PropertyWidgetCollection.registerWidget(PropertyWidgetCollection.java:92)
	at org.datacleaner.panels.AbstractComponentBuilderPanel$1.getPropertyWidget(AbstractComponentBuilderPanel.java:203)
	at org.datacleaner.widgets.properties.PropertyWidgetPanel.addProperties(PropertyWidgetPanel.java:38)
	at org.datacleaner.panels.AbstractComponentBuilderPanel.buildTaskPane(AbstractComponentBuilderPanel.java:207)
	at org.datacleaner.panels.AbstractComponentBuilderPanel.init(AbstractComponentBuilderPanel.java:142)
	at org.datacleaner.panels.AbstractComponentBuilderPanel.createJComponent(AbstractComponentBuilderPanel.java:112)
	at org.datacleaner.windows.ComponentConfigurationDialog.getDialogContent(ComponentConfigurationDialog.java:163)
	at org.datacleaner.windows.AbstractDialog.getWindowContent(AbstractDialog.java:167)
	at org.datacleaner.windows.AbstractDialog.initialize(AbstractDialog.java:117)
	at org.datacleaner.windows.AbstractDialog.setVisible(AbstractDialog.java:140)
	at org.datacleaner.windows.AbstractDialog.open(AbstractDialog.java:90)
	at org.datacleaner.widgets.visualization.JobGraphActions.showConfigurationDialog(JobGraphActions.java:81)
	at org.datacleaner.widgets.visualization.JobGraphLinkPainter.createLink(JobGraphLinkPainter.java:241)
	at org.datacleaner.widgets.visualization.JobGraphLinkPainter.endLink(JobGraphLinkPainter.java:150)
	at org.datacleaner.widgets.visualization.JobGraphMouseListener.graphReleased(JobGraphMouseListener.java:257)
	at edu.uci.ics.jung.visualization.control.MouseListenerTranslator.mouseReleased(MouseListenerTranslator.java:87)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
This particular stack trace is from linking a ValueDistributionAnalyzer to "Complete rows" of CompletenessAnalyzer.

**Comment by tomaszguzialek** [comment]
It might be something with Completeness Analyzer working on a subset of input columns available - input datastore has 4 columns, but Completeness Analyzer has only two checkboxes ticked.
