### ISSUE TITLE
Ensure that Freemarker is using slf4j

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#707]
Although we seem to be following the guidelines set by Freemarker [1] we have now a report that it fails at runtime to resolve the right logger. Here's a stack trace:

```
java.lang.NoClassDefFoundError: org/apache/log4j/or/RendererMap
	at org.apache.log4j.Hierarchy.<init>(Hierarchy.java:97) ~[apache-log4j-extras-1.2.17.jar:na]
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:82) ~[apache-log4j-extras-1.2.17.jar:na]
	at org.apache.log4j.Logger.getLogger(Logger.java:104) ~[apache-log4j-extras-1.2.17.jar:na]
	at freemarker.log._Log4jLoggerFactory.getLogger(_Log4jLoggerFactory.java:29) ~[freemarker-2.3.22.jar:2.3.22]
	at freemarker.log.Logger.getLogger(Logger.java:357) ~[freemarker-2.3.22.jar:2.3.22]
	at freemarker.template.Configuration.<clinit>(Configuration.java:125) ~[freemarker-2.3.22.jar:2.3.22]
	at org.datacleaner.monitor.wizard.common.AbstractFreemarkerWizardPage.getFormInnerHtml(AbstractFreemarkerWizardPage.java:46) ~[DataCleaner-monitor-api-4.0.11.jar:na]
```

From this it looks like Freemarker selects to use log4j as the logging mechanism. That should be alright because we also have log4j-over-slf4j, but the apache-log4j-extras somehow get in the way it seems.

Investigate it further and sort it out.

[1] http://freemarker.org/docs/pgui_misc_logging.html

**Comment by kaspersorensen** [comment]
Confirmed that for now this can be worked around by deleting ```WEB-INF/lib/apache-log4j-extras-1.2.17.jar```.

I will notify the user who reported it and add apache-log4j-extras to our ban list of dependencies to avoid this in future releases.
