### ISSUE TITLE
Error in job template 'Copy employees to customer table.analysis.xml' 

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#778]
Stacktrace: 

```

14:35:47ERROR: An error occurred in the analyzer: orderdb - CUSTOMERS (18 columns)

Could not execute batch: org.hsqldb.jdbc.jdbcPreparedStatement@c13e4ec[sql=[INSERT INTO PUBLIC."CUSTOMERS" (CUSTOMERNUMBER,CUSTOMERNAME,CONTACTLASTNAME,CONTACTFIRSTNAME,PHONE,ADDRESSLINE1,CITY,COUNTRY,SALESREPEMPLOYEENUMBER) VALUES (?,?,?,?,?,?,?,?,?)], parameters=[[5023], [My company], [Gerard], [Martin], [My phone no], [My address], [My city], [My country], [1702]]]: failed batch

org.apache.metamodel.MetaModelException: Could not execute batch: org.hsqldb.jdbc.jdbcPreparedStatement@c13e4ec[sql=[INSERT INTO PUBLIC."CUSTOMERS" (CUSTOMERNUMBER,CUSTOMERNAME,CONTACTLASTNAME,CONTACTFIRSTNAME,PHONE,ADDRESSLINE1,CITY,COUNTRY,SALESREPEMPLOYEENUMBER) VALUES (?,?,?,?,?,?,?,?,?)], parameters=[[5023], [My company], [Gerard], [Martin], [My phone no], [My address], [My city], [My country], [1702]]]: failed batch
	at org.apache.metamodel.jdbc.JdbcUtils.wrapException(JdbcUtils.java:68)
	at org.apache.metamodel.jdbc.JdbcBatchUpdateCallback.closePreparedStatement(JdbcBatchUpdateCallback.java:64)
	at org.apache.metamodel.jdbc.JdbcUpdateCallback.close(JdbcUpdateCallback.java:80)
	at org.apache.metamodel.jdbc.JdbcDataContext.executeUpdate(JdbcDataContext.java:789)
	at org.datacleaner.beans.writers.InsertIntoTableAnalyzer.run(InsertIntoTableAnalyzer.java:447)
	at org.datacleaner.beans.writers.InsertIntoTableAnalyzer.run(InsertIntoTableAnalyzer.java:80)
	at org.datacleaner.util.WriteBuffer.flushBuffer(WriteBuffer.java:84)
	at org.datacleaner.util.WriteBuffer.addToBuffer(WriteBuffer.java:60)
	at org.datacleaner.beans.writers.InsertIntoTableAnalyzer.run(InsertIntoTableAnalyzer.java:381)
	at org.datacleaner.job.runner.AnalyzerConsumer.consumeInternal(AnalyzerConsumer.java:71)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.processNext(ConsumeRowHandlerDelegate.java:90)
	at org.datacleaner.job.runner.TransformerConsumer.consumeInternal(TransformerConsumer.java:115)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:146)
	at org.datacleaner.job.tasks.ConsumeRowTask.execute(ConsumeRowTask.java:51)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: failed batch
	at org.hsqldb.jdbc.jdbcStatement.executeBatch(Unknown Source)
	at org.hsqldb.jdbc.jdbcPreparedStatement.executeBatch(Unknown Source)
	at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.apache.metamodel.jdbc.JdbcBatchUpdateCallback.closePreparedStatement(JdbcBatchUpdateCallback.java:45)
	... 20 more

```

**Comment by kaspersorensen** [comment]
This happens because orderdb is read-only. Not sure we can fix it except if we get a new database or something like that.

**Comment by LosD** [comment]
Since it is just a template, I don't really think it is a big problem. However, the error message is horrendous.
