### ISSUE TITLE
ClassCastException in Pattern finder with column type Object

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#791]
Experienced this while trying Pattern finder on a union'ed field that had type Object. It was a combination of Strings and Integers.

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.datacleaner.beans.stringpattern.PatternFinderAnalyzer.run(PatternFinderAnalyzer.java:194)
	at org.datacleaner.job.runner.AnalyzerConsumer.consumeInternal(AnalyzerConsumer.java:71)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:146)
	at org.datacleaner.job.runner.OutputDataStreamRowCollector.putRow(OutputDataStreamRowCollector.java:65)
	at org.datacleaner.job.runner.OutputDataStreamRowCollector.putValues(OutputDataStreamRowCollector.java:58)
	at org.datacleaner.components.fuse.FuseStreamsComponent.run(FuseStreamsComponent.java:114)
	at org.datacleaner.api.MultiStreamComponent.transform(MultiStreamComponent.java:38)
	at org.datacleaner.job.runner.TransformerConsumer.consumeInternal(TransformerConsumer.java:103)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:146)
	at org.datacleaner.job.tasks.ConsumeRowTask.execute(ConsumeRowTask.java:51)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source) 
```

**Comment by LosD** [comment]
This seems to be an error in our output data stream _Link "xxx" to..._ logic. If I try manually to link it from the configuration dialog, it doesn't show the object column in the stream:
![image](https://cloud.githubusercontent.com/assets/1282832/10480249/6737a4cc-7269-11e5-87df-5cf3b4913faf.png)

However, if I use _Link "output" to..._:
![image](https://cloud.githubusercontent.com/assets/1282832/10480269/91379c82-7269-11e5-8ee4-6e8ddcd45737.png)

![image](https://cloud.githubusercontent.com/assets/1282832/10480281/9eab5f70-7269-11e5-994b-d8efb5c18c49.png)

![image](https://cloud.githubusercontent.com/assets/1282832/10480287/a801e616-7269-11e5-9e4c-baa7eac208d6.png)

**Comment by LosD** [comment]
The same happens for "normal" _Link to..._. For the pattern finder, it seems to just indiscriminately take the first row, no matter if the type fits.
