### ISSUE TITLE
Transformer's "Write Data" fails on execute

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#864]
It seems that we have a bug in the transformer feature that generates a data writer, at least in the case where that writer is an Excel writer. The generated _Create Excel spreadsheet_ analyzer will fail when executing the job.

### Steps to reproduce
1. Build job from scratch with i.e. _Customers_ datastore.
2. Link a _Country standardizer_ to the table.
3. Click _Write data_ and choose an Excel datastore.
4. Run job.

### Expected outcome
Job runs, data in new Excel spreadsheet.

### Actual outcome
Job fails, with varying Exceptions.

Sometimes
```
java.lang.NullPointerException
	at org.apache.metamodel.excel.ExcelUpdateCallback.getLastRowNum(ExcelUpdateCallback.java:131)
	at org.apache.metamodel.excel.ExcelUpdateCallback.createRow(ExcelUpdateCallback.java:125)
	at org.apache.metamodel.excel.ExcelInsertBuilder.execute(ExcelInsertBuilder.java:52)
	at org.datacleaner.output.AbstractMetaModelOutputWriter$1.run(AbstractMetaModelOutputWriter.java:94)
	at org.apache.metamodel.excel.ExcelDataContext.executeUpdate(ExcelDataContext.java:232)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.flushBuffer(AbstractMetaModelOutputWriter.java:85)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.addToBuffer(AbstractMetaModelOutputWriter.java:78)
	at org.datacleaner.output.MetaModelOutputRow.write(MetaModelOutputRow.java:62)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.writeRow(AbstractOutputWriterAnalyzer.java:79)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.run(AbstractOutputWriterAnalyzer.java:68)
	at org.datacleaner.job.runner.AnalyzerConsumer.consumeInternal(AnalyzerConsumer.java:71)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:67)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.processNext(ConsumeRowHandlerDelegate.java:90)
	at org.datacleaner.job.runner.TransformerConsumer.consumeInternal(TransformerConsumer.java:115)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.processNext(ConsumeRowHandlerDelegate.java:90)
	at org.datacleaner.job.runner.TransformerConsumer.consumeInternal(TransformerConsumer.java:115)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:64)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:146)
	at org.datacleaner.job.tasks.ConsumeRowTask.execute(ConsumeRowTask.java:51)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

And sometimes a NullPointerException with no stacktrace (Maybe available if JVM configured with ```-XX:-OmitStackTraceInFastThrow```.

If the file exists without the sheet, this exception will be thrown instead:
```
WARN  10:41:44.040 [analyzerbeans-pool1-thread-2] ErrorAwareAnalysisListener - Exception stack trace:
java.lang.ArrayIndexOutOfBoundsException: 11
	at org.apache.metamodel.data.AbstractRowBuilder.value(AbstractRowBuilder.java:108)
	at org.apache.metamodel.data.AbstractRowBuilder.value(AbstractRowBuilder.java:103)
	at org.datacleaner.output.AbstractMetaModelOutputWriter$1.run(AbstractMetaModelOutputWriter.java:92)
	at org.apache.metamodel.excel.ExcelDataContext.executeUpdate(ExcelDataContext.java:232)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.flushBuffer(AbstractMetaModelOutputWriter.java:85)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.addToBuffer(AbstractMetaModelOutputWriter.java:78)
	at org.datacleaner.output.MetaModelOutputRow.write(MetaModelOutputRow.java:62)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.writeRow(AbstractOutputWriterAnalyzer.java:79)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.run(AbstractOutputWriterAnalyzer.java:68)
	at org.datacleaner.job.runner.AnalyzerConsumer.consumeInternal(AnalyzerConsumer.java:71)
	at org.datacleaner.job.runner.AbstractRowProcessingConsumer.consume(AbstractRowProcessingConsumer.java:161)
	at org.datacleaner.job.runner.ConsumeRowHandlerDelegate.consume(ConsumeRowHandlerDelegate.java:67)
	at org.datacleaner.job.runner.ConsumeRowHandler.consumeRow(ConsumeRowHandler.java:146)
	at org.datacleaner.job.tasks.ConsumeRowTask.execute(ConsumeRowTask.java:51)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Please note that none of this happens if the _Create Excel spreadsheet_ analyzer is created manually.

**Comment by kaspersorensen** [comment]
I tried to reproduce at home, but couldn't.
So maybe a hint to further reproduce: This did not seem to happen on Mac OS X. To my knowledge we have only reproduced it on Windows.

**Comment by LosD** [comment]
That sounds like more locking issues, then :-1: :(

**Comment by kaspersorensen** [comment]
Strange observation: It doesn't happen on a concatenator. This was also what I tried on my mac, so the hypothesis around Windows-specifics is not really valid (or at least confirmed) anymore.

**Comment by kaspersorensen** [comment]
Found it! It has to do with the length of the generated sheet name. Here's a screenshot of the created sheet and what is being resolved in Java:

![image](https://cloud.githubusercontent.com/assets/291450/10933467/eca2f312-82d8-11e5-82b5-6c387e8d40eb.png)

So short term fix: Simply do more checking of sheet names, just like we already remove illegal chars etc.
