### ISSUE TITLE
Error on right click into canvas

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#994]
After clicking on a canvas in a new workflow, there is an error dialog.
Expected Behavior

java.util.Collections$UnmodifiableCollection cannot be cast to java.util.List

![dcclickerror](https://cloud.githubusercontent.com/assets/13213915/11627589/f059cfc6-9ceb-11e5-8c67-a4cf7465d14f.png)

**Comment by kaspersorensen** [comment]
Would be more clear if you also add the stack trace - right now it cannot be seen in the screenshot.

**Comment by jhorcicka** [comment]
It is a problem from my previous issue. 

ERROR 14:15:20 DCUncaughtExceptionHandler - Thread AWT-EventQueue-0 threw uncaught exception
java.lang.ClassCastException: java.util.Collections$UnmodifiableCollection cannot be cast to java.util.List
	at org.datacleaner.widgets.DescriptorMenuBuilder.getFinalComponentDescriptors(DescriptorMenuBuilder.java:177)
	at org.datacleaner.widgets.DescriptorMenuBuilder.createMenuStructure(DescriptorMenuBuilder.java:125)
	at org.datacleaner.widgets.DescriptorMenuBuilder.initialize(DescriptorMenuBuilder.java:237)
	at org.datacleaner.widgets.DescriptorMenuBuilder.addItemsToMenu(DescriptorMenuBuilder.java:116)
	at org.datacleaner.widgets.visualization.JobGraphMouseListener.onCanvasRightClicked(JobGraphMouseListener.java:242)
	at org.datacleaner.widgets.visualization.JobGraphMouseListener.mouseReleased(JobGraphMouseListener.java:343)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
