### ISSUE TITLE
Write to Excel Exception-Possible cause:multiple columns with the same name

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#998]
Exception while trying to write to Excel 
<code>
java.lang.ArrayIndexOutOfBoundsException: 14
	at org.apache.metamodel.data.AbstractRowBuilder.value(AbstractRowBuilder.java:108)
	at org.apache.metamodel.data.AbstractRowBuilder.value(AbstractRowBuilder.java:103)
	at org.datacleaner.output.AbstractMetaModelOutputWriter$1.run(AbstractMetaModelOutputWriter.java:92)
	at org.apache.metamodel.excel.ExcelDataContext.executeUpdate(ExcelDataContext.java:232)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.flushBuffer(AbstractMetaModelOutputWriter.java:85)
	at org.datacleaner.output.AbstractMetaModelOutputWriter.close(AbstractMetaModelOutputWriter.java:105)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.getResult(AbstractOutputWriterAnalyzer.java:58)
	at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.getResult(AbstractOutputWriterAnalyzer.java:35)
	at org.datacleaner.job.tasks.CollectResultsTask.execute(CollectResultsTask.java:60)
	at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</code>

scenario: 
-  Start a job a with a file with addresses 
-  Add 'Internation address correction' transformer 
-  Configure the transformer 
-  Selected 'Write data' button and select 'Create Excel Spreadsheet' 
-  Press execute. 

International Address Correction Mapping: 

![image](https://cloud.githubusercontent.com/assets/6339923/11689334/bf94c10a-9e91-11e5-893a-1c06bc5bc077.png)

Create Excel SpreadSheet Analyzer mapping 

![image](https://cloud.githubusercontent.com/assets/6339923/11689451/5ddf998e-9e92-11e5-8e47-137d0f759baa.png)

**Comment by kaspersorensen** [comment]
My guess is that this has to do with the duplicate column name "City". At least that's something we could test quite easily.

**Comment by kaspersorensen** [comment]
Confirmed that suspicion. It also happens here:

![image](https://cloud.githubusercontent.com/assets/291450/11714679/3a0f6a3e-9f3c-11e5-920a-d62fdd2ed899.png)
